# Generated by Django 3.2.8 on 2021-10-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='name',
        ),
    ]
